site_stock/config/routes.rb
SiteStock::Application.routes.draw do
  resources :searches

  resources :medios

  devise_for :users

  resources :ip_types

  resources :isles

  resources :dependencies

  resources :ips

  resources :sites

  get "home/index"

   root :to => 'home#index'

end

site_stock/app/models/ip.rb
class Ip < ActiveRecord::Base
  attr_accessible :ID_IP_TYPES, :ID_SITES, :IP
end

site_stock/app/models/ip_type.rb
class IpType < ActiveRecord::Base
  attr_accessible :DESCRIPCION
end

site_stock/app/controllers/ips_controller.rb
class IpsController < ApplicationController
  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ips }
    end
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
    @ip = Ip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ip }
    end
  end

  # GET /ips/new
  # GET /ips/new.json
  def new
    @ip = Ip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ip }
    end
  end

  # GET /ips/1/edit
  def edit
    @ip = Ip.find(params[:id])
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(params[:ip])

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, :notice => 'Ip was successfully created.' }
        format.json { render :json => @ip, :status => :created, :location => @ip }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ips/1
  # PUT /ips/1.json
  def update
    @ip = Ip.find(params[:id])

    respond_to do |format|
      if @ip.update_attributes(params[:ip])
        format.html { redirect_to @ip, :notice => 'Ip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip = Ip.find(params[:id])
    @ip.destroy

    respond_to do |format|
      format.html { redirect_to ips_url }
      format.json { head :no_content }
    end
  end
end

site_stock/app/helpers/i_ps_helper.rb
module IPsHelper
end

site_stock/app/views/ips/_form.html.erb
<%= form_for(@ip) do |f| %>
  <% if @ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
      <% @ip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :IP %><br />
    <%= f.text_field :IP %>
  </div>
  <div class="field">
    <%= f.label :ID_SITES %><br />
    <%= f.number_field :ID_SITES %>
  </div>
  <div class="field">
    <%= f.label :ID_IP_TYPES %><br />
    <%= f.text_field :ID_IP_TYPES %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site_stock/app/views/ips/edit.html.erb
<h1>Editing ip</h1>

<%= render 'form' %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

site_stock/app/views/ips/index.html.erb
<h1>Listing ips</h1>

<table>
  <tr>
    <th>Ip</th>
    <th>Id sites</th>
    <th>Id ip types</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ips.each do |ip| %>
  <tr>
    <td><%= ip.IP %></td>
    <td><%= ip.ID_SITES %></td>
    <td><%= ip.ID_IP_TYPES %></td>
    <td><%= link_to 'Show', ip %></td>
    <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
    <td><%= link_to 'Destroy', ip, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ip', new_ip_path %>

site_stock/app/views/ips/new.html.erb
<h1>New ip</h1>

<%= render 'form' %>

<%= link_to 'Back', ips_path %>

site_stock/app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ip:</b>
  <%= @ip.IP %>
</p>

<p>
  <b>Id sites:</b>
  <%= @ip.ID_SITES %>
</p>

<p>
  <b>Id ip types:</b>
  <%= @ip.ID_IP_TYPES %>
</p>


<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>