site_stock/config/routes.rb
SiteStock::Application.routes.draw do
  resources :searches

  resources :medios

  devise_for :users

  resources :ip_types

  resources :isles

  resources :dependencies

  resources :ips

  resources :sites

  get "home/index"

   root :to => 'home#index'

end

site_stock/app/models/search.rb
class Search < ActiveRecord::Base

attr_accessible :CODiGO, :NOMBRE, :ISLA, :MEDIO, :TIPO, :IP

def sites
  @sites ||= find_sites
end

private

def find_sites
  Sites.find(:all, :conditions => conditions)
end

def keyword_conditions
  ["sites.COD_SITE LIKE ?", "%#{CODiGO}%"] unless CODiGO.blank?
end

def conditions
  [conditions_clauses.join(' AND '), *conditions_options]
end

def conditions_clauses
  conditions_parts.map { |condition| condition.first }
end

def conditions_options
  conditions_parts.map { |condition| condition[1..-1] }.flatten
end

def conditions_parts
  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end

end

site_stock/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @searches }
    end
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @search = Search.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @search }
    end
  end

  # GET /searches/new
  # GET /searches/new.json
  def new
    @search = Search.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @search }
    end
  end

  # GET /searches/1/edit
  def edit
    @search = Search.find(params[:id])
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(params[:search])

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, :notice => 'Search was successfully created.' }
        format.json { render :json => @search, :status => :created, :location => @search }
      else
        format.html { render :action => "new" }
        format.json { render :json => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /searches/1
  # PUT /searches/1.json
  def update
    @search = Search.find(params[:id])

    respond_to do |format|
      if @search.update_attributes(params[:search])
        format.html { redirect_to @search, :notice => 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end
end

site_stock/app/helpers/searc_hes_helper.rb
module SearcHesHelper
end

site_stock/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CODiGO %><br />
    <%= f.text_field :CODiGO %>
  </div>
  <div class="field">
    <%= f.label :NOMBRE %><br />
    <%= f.text_field :NOMBRE %>
  </div>
  <div class="field">
    <%= f.label :ISLA %><br />
    <%= f.text_field :ISLA %>
  </div>
  <div class="field">
    <%= f.label :MEDIO %><br />
    <%= f.number_field :MEDIO %>
  </div>  
  <div class="field">
    <%= f.label :TIPO %><br />
    <%= f.number_field :TIPO %>
  </div>
  <div class="field">
    <%= f.label :IP %><br />
    <%= f.text_field :IP %>
  </div>
  <div class="field">
    <%= f.label :new %><br />
    <%= f.text_field :new %>
  </div>
  <div class="field">
    <%= f.label :show %><br />
    <%= f.text_field :show %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site_stock/app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

site_stock/app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Isla</th>
    <th>Medio</th>
    <th>Isla</th>
    <th>Tipo</th>
    <th>Ip</th>
    <th>New</th>
    <th>Show</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @searches.each do |search| %>
  <tr>
    <td><%= search.CODiGO %></td>
    <td><%= search.NOMBRE %></td>
    <td><%= search.ISLA %></td>
    <td><%= search.MEDIO %></td>
    <td><%= search.ISLA %></td>
    <td><%= search.TIPO %></td>
    <td><%= search.IP %></td>
    <td><%= search.new %></td>
    <td><%= search.show %></td>
    <td><%= link_to 'Show', search %></td>
    <td><%= link_to 'Edit', edit_search_path(search) %></td>
    <td><%= link_to 'Destroy', search, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search', new_search_path %>

site_stock/app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

site_stock/app/views/searches/show.html.erb
<%= render :partial => @search.sites %>