site_stock/config/routes.rb
SiteStock::Application.routes.draw do
  resources :searches

  resources :medios

  devise_for :users

  resources :ip_types

  resources :isles

  resources :dependencies

  resources :ips

  resources :sites

  get "home/index"

   root :to => 'home#index'

end

site_stock/app/models/isle.rb
class Isle < ActiveRecord::Base

  attr_accessible :NOMBRE_ISLA

unless params[:id].blank?
  where << "id IN (:id)"
end

        OR

unless params[:id].blank?
  where << "id IN (  #{params[:id].join(',')})"
end

end

site_stock/app/controllers/isles_controller.rb
class IslesController < ApplicationController
  # GET /isles
  # GET /isles.json
  def index
    @isles = Isle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @isles }
    end
  end

  # GET /isles/1
  # GET /isles/1.json
  def show
    @isle = Isle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @isle }
    end
  end

  # GET /isles/new
  # GET /isles/new.json
  def new
    @isle = Isle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @isle }
    end
  end

  # GET /isles/1/edit
  def edit
    @isle = Isle.find(params[:id])
  end

  # POST /isles
  # POST /isles.json
  def create
    @isle = Isle.new(params[:isle])

    respond_to do |format|
      if @isle.save
        format.html { redirect_to @isle, :notice => 'Isle was successfully created.' }
        format.json { render :json => @isle, :status => :created, :location => @isle }
      else
        format.html { render :action => "new" }
        format.json { render :json => @isle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /isles/1
  # PUT /isles/1.json
  def update
    @isle = Isle.find(params[:id])

    respond_to do |format|
      if @isle.update_attributes(params[:isle])
        format.html { redirect_to @isle, :notice => 'Isle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @isle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /isles/1
  # DELETE /isles/1.json
  def destroy
    @isle = Isle.find(params[:id])
    @isle.destroy

    respond_to do |format|
      format.html { redirect_to isles_url }
      format.json { head :no_content }
    end
  end
end

site_stock/app/helpers/isl_es_helper.rb
module IslEsHelper
end

site_stock/app/views/isles/_form.html.erb
<%= form_for(@isle) do |f| %>
  <% if @isle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@isle.errors.count, "error") %> prohibited this isle from being saved:</h2>

      <ul>
      <% @isle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NOMBRE_ISLA %><br />
    <%= f.text_field :NOMBRE_ISLA %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site_stock/app/views/isles/edit.html.erb
<h1>Editing isle</h1>

<%= render 'form' %>

<%= link_to 'Show', @isle %> |
<%= link_to 'Back', isles_path %>

site_stock/app/views/isles/index.html.erb
<h1>Listing isles</h1>

<table>
  <tr>
    <th>Nombre isla</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @isles.each do |isle| %>
  <tr>
    <td><%= isle.NOMBRE_ISLA %></td>
    <td><%= link_to 'Show', isle %></td>
    <td><%= link_to 'Edit', edit_isle_path(isle) %></td>
    <td><%= link_to 'Destroy', isle, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Isle', new_isle_path %>

site_stock/app/views/isles/new.html.erb
<h1>New isle</h1>

<%= render 'form' %>

<%= link_to 'Back', isles_path %>

site_stock/app/views/isles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre isla:</b>
  <%= @isle.NOMBRE_ISLA %>
</p>


<%= link_to 'Edit', edit_isle_path(@isle) %> |
<%= link_to 'Back', isles_path %>