site_stock/config/routes.rb
SiteStock::Application.routes.draw do
  resources :searches

  resources :medios

  devise_for :users

  resources :ip_types

  resources :isles

  resources :dependencies

  resources :ips

  resources :sites

  get "home/index"

   root :to => 'home#index'

end

site_stock/app/models/medio.rb
class Medio < ActiveRecord::Base
  # attr_accessible :title, :body
end

site_stock/app/controllers/medios_controller.rb
class MediosController < ApplicationController
  # GET /medios
  # GET /medios.json
  def index
    @medios = Medio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @medios }
    end
  end

  # GET /medios/1
  # GET /medios/1.json
  def show
    @medio = Medio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @medio }
    end
  end

  # GET /medios/new
  # GET /medios/new.json
  def new
    @medio = Medio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @medio }
    end
  end

  # GET /medios/1/edit
  def edit
    @medio = Medio.find(params[:id])
  end

  # POST /medios
  # POST /medios.json
  def create
    @medio = Medio.new(params[:medio])

    respond_to do |format|
      if @medio.save
        format.html { redirect_to @medio, :notice => 'Medio was successfully created.' }
        format.json { render :json => @medio, :status => :created, :location => @medio }
      else
        format.html { render :action => "new" }
        format.json { render :json => @medio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /medios/1
  # PUT /medios/1.json
  def update
    @medio = Medio.find(params[:id])

    respond_to do |format|
      if @medio.update_attributes(params[:medio])
        format.html { redirect_to @medio, :notice => 'Medio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @medio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /medios/1
  # DELETE /medios/1.json
  def destroy
    @medio = Medio.find(params[:id])
    @medio.destroy

    respond_to do |format|
      format.html { redirect_to medios_url }
      format.json { head :no_content }
    end
  end
end

site_stock/app/helpers/medios_helper.rb
module MediosHelper
end

site_stock/app/views/medios/_form.html.erb
<%= form_for(@medio) do |f| %>
  <% if @medio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medio.errors.count, "error") %> prohibited this medio from being saved:</h2>

      <ul>
      <% @medio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site_stock/app/views/medios/edit.html.erb
<h1>Editing medio</h1>

<%= render 'form' %>

<%= link_to 'Show', @medio %> |
<%= link_to 'Back', medios_path %>

site_stock/app/views/medios/index.html.erb
<h1>Listing medios</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @medios.each do |medio| %>
  <tr>
    <td><%= link_to 'Show', medio %></td>
    <td><%= link_to 'Edit', edit_medio_path(medio) %></td>
    <td><%= link_to 'Destroy', medio, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Medio', new_medio_path %>

site_stock/app/views/medios/new.html.erb
<h1>New medio</h1>

<%= render 'form' %>

<%= link_to 'Back', medios_path %>

site_stock/app/views/medios/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_medio_path(@medio) %> |
<%= link_to 'Back', medios_path %>